---
title: "Reward Mechanism Data"
author: "Candice"
date: "2023-07-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load required packages
library(dplyr)
library(purrr)
library(broom)
library(ggplot2)
library(RColorBrewer)
library(tidyverse)
library(anytime)
library(car)
library(pwr)
library(psych)

# Define the directory path
dir_path <- "C:/Users/晨希/Desktop/Psychological Science/dissertation/Reward Mechanism Data"

# Get the list of CSV files
file_list <- list.files(path = dir_path, full.names = TRUE, pattern = "\\.csv$")

# Read and bind all CSV files
data_list <- file_list %>%
  map(function(file_name) {
    data <- read.csv(file_name, stringsAsFactors = FALSE)
    if (!"user" %in% names(data)) {
      data$user <- NA
    } else {
      data$user <- as.character(data$user)
    }
    # Check if "objective_reached" column exists, if so, convert it to character type
    if ("objective_reached" %in% names(data)) {
      data$objective_reached <- as.character(data$objective_reached)
    }
    # Check if "cashed_out" column exists, if so, convert it to character type
    if ("cashed_out" %in% names(data)) {
      data$cashed_out <- as.character(data$cashed_out)
    }
    return(data)
  }) %>%
  set_names(gsub(paste0(dir_path, "/"), "", file_list, fixed = TRUE)) %>%
  bind_rows(.id = "filename")
# Change specific value
data_list <- data_list %>% 
  mutate(user = if_else(user == 280, "28E1", user))
# View the data
head(data_list)
```

```{r}
# Delete unnecessary columns
data_list <- select(data_list, -c(filename, X, id))
# Convert the date column to date format
data_list$date <- anydate(data_list$date)
# Delete all rows before 2023-06-26
data_list <- data_list[data_list$date >= as.Date("2023-06-26"),]
#Delete useless data
data_list <- data_list[!data_list$user %in% c("06DS", "07EI", "12AE", "23MI", "182", "13SK", "25J1", "242K"),]
#sort data by 'user' first and then by 'date'
data_list <- data_list[order(data_list$user, data_list$date), ]
head(data_list)
```

```{r}
# Create a function to determine the reward scheme
determine_reward_condition <- function(starting_at, objective, amount) {
  # Create a character vector to store the result
  result <- character(length(starting_at))
  
  # Convert all inputs to character type
  starting_at <- as.character(starting_at)
  objective <- as.character(objective)
  amount <- as.character(amount)
  
  # Concatenate all inputs
  input_str <- paste0(starting_at, "-", objective, "-", amount, collapse = ";")
  
  # Define strings for each reward scheme
  condition1_str <- "0-7000-1.5"
  condition2_str <- "0-700-0.3;700-1750-0.3;1750-3150-0.3;3150-4900-0.3;4900-7000-0.3"
  condition3_str <- "0-1400-0.3;1400-2800-0.3;2800-4200-0.3;4200-5600-0.3;5600-7000-0.3"
  condition4_str <- "0-1400-0.1;1400-2800-0.2;2800-4200-0.3;4200-5600-0.4;5600-7000-0.5"
  
  # Check if the input string matches a reward scheme
  if(input_str == condition1_str) {
    result <- "condition1"
  } else if(input_str == condition2_str) {
    result <- "condition2"
  } else if(input_str == condition3_str) {
    result <- "condition3"
  } else if(input_str == condition4_str) {
    result <- "condition4"
  } else {
    result <- NA
  }
  
  return(result)
}

# Sort the dataframe and group it
data_list <- data_list %>%
  arrange(user, date, starting_at) %>%
  group_by(user, date)

# Apply the function to the dataframe to create a new reward_scheme column
data_list <- data_list %>%
  mutate(reward_condition = determine_reward_condition(starting_at, objective, amount)) %>%
  ungroup()

# View the dataframe
head(data_list)
```

```{r}
# Assign data within the date range to a new dataframe
data_list_new <- data_list[data_list$date >= as.Date("2023-06-26") & data_list$date <= as.Date("2023-07-14"),]

# Only keep data from the weekends
data_list_new <- data_list_new[weekdays(data_list_new$date) %in% c("星期六", "星期日"),]
```

```{r}
# Read in Big Five Personality data
big_five_data <- read.csv("C:/Users/晨希/Desktop/Psychological Science/dissertation/Big Five Personality Data/merged_data.csv", stringsAsFactors = FALSE)
# Merge big_five_data and data_list, with unique_code and user as the keys
Personality_reward <- data_list %>%
  left_join(big_five_data, by = c("user" = "Unique_Code"))
describe(big_five_data)
# View the dataframe
head(Personality_reward)
```

```{r}
# Sum up reward amount by date and user
Personality_reward_daily <- Personality_reward %>%
  group_by(user, date) %>%
  summarise(daily_amount = sum(ifelse(objective_reached == "True", amount, 0)), reward_condition = first(reward_condition)) 

```

```{r}
# Create a new vector for column names
new_names <- c("O", "C", "E", "A", "N")

# Find all columns ending with "_Rank"
rank_columns <- grep("_Rank$", names(Personality_reward), value = TRUE)

# Change the names of these columns to the new names
names(Personality_reward)[names(Personality_reward) %in% rank_columns] <- new_names

# Check if the change is successful
names(Personality_reward)

# Recode the 'O', 'C', 'E', 'A', 'N' columns
Personality_reward <- Personality_reward %>%
  mutate(across(c(O, C, E, A, N),
                ~ case_when(
                    . == "Very Low" ~ 1,
                    . == "Low" ~ 2,
                    . == "Average" ~ 3,
                    . == "High" ~ 4,
                    . == "Very High" ~ 5,
                    TRUE ~ as.numeric(.)
                  )
        )
  )
Personality_reward_daily <- Personality_reward_daily %>%
  left_join(Personality_reward[,c("user", "date", "O", "C", "E", "A", "N")], by = c("user", "date"))
```

```{r}
# Create a linear regression model with interaction terms
model_interactions <- lm(daily_amount ~ O * reward_condition + C * reward_condition + 
                            E * reward_condition + A * reward_condition + 
                            N * reward_condition, data = Personality_reward_daily)

# View the model summary
summary(model_interactions)

glance_results <- glance(model_interactions)
write.csv(glance_results, "glance_results.csv")
```

```{r}
# Model for weekdays
# Assuming your date variable is named 'date
Personality_reward_daily$weekdays <- weekdays(Personality_reward_daily$date)

# Create is_weekend variable
Personality_reward_daily$is_weekend <- Personality_reward_daily$weekdays %in% c("星期六", "星期日")

# Create a dataframe that only includes weekend data
Personality_reward_daily_weekend <- Personality_reward_daily %>%
  filter(is_weekend)  # Select rows where 'is_weekend' is TRUE

# Remove weekend data
Personality_reward_daily_weekdays <- Personality_reward_daily %>%
  filter(!is_weekend)  # Select rows where 'is_weekend' is not TRUE

result <- Personality_reward_daily_weekend %>%
  group_by(reward_scheme) %>%
  summarise(
    Mean = mean(daily_amount, na.rm = TRUE),
    SD = sd(daily_amount, na.rm = TRUE)
  )

# Create a linear regression model with interaction terms
model_interactions_weekdays <- lm(daily_amount ~ O * reward_condition + C * reward_condition + 
                            E * reward_condition + A * reward_condition + 
                            N * reward_condition, data = Personality_reward_daily_weekdays)
model_summary <- summary(model_interactions_weekdays)
plot(model_interactions_weekdays)
vif(model_interactions_weekdays)
pwr.r.test(r = 0.3, sig.level = 0.05, power = 0.8)

model_interactions_weekend <- lm(daily_amount ~ O * reward_condition + C * reward_condition + 
                            E * reward_condition + A * reward_condition + 
                            N * reward_condition, data = Personality_reward_daily_weekend)
model_summary <- summary(model_interactions_weekend)

# Create data subsets for high N group and low N group
high_N_data <- subset(Personality_reward_daily_weekdays, N > 3)
low_N_data <- subset(Personality_reward_daily_weekdays, N <= 3)

# Run interaction model in high N group
model_interactions_weekdays_high <- lm(daily_amount ~ O * reward_scheme + C * reward_scheme + 
                                        E * reward_scheme + A * reward_scheme + 
                                        N * reward_scheme, data = high_N_data)
summary(model_interactions_weekdays_high)

# Run interaction model in low N group
model_interactions_weekdays_low <- lm(daily_amount ~ O * reward_condition + C * reward_condition + 
                                       E * reward_condition + A * reward_condition + 
                                       N * reward_condition, data = low_N_data)
summary(model_interactions_weekdays_low)

# Use the glance function to get model-level statistics
glance_results <- glance(model_interactions_weekdays)
write.csv(glance_results, "glance_results_weekdays.csv")

augment_results <- augment(model_interactions_weekdays)

# Write the data to a CSV file
write.csv(model_stats_weekdays, file = "model_stats_weekdays.csv")
```

```{r}
# Write the data to a CSV file
model_interactions <- tidy(model_interactions)
model_interactions_weekdays <- tidy(model_interactions_weekdays)
write.csv(model_interactions, "model_interactions.csv", row.names = FALSE)
write.csv(model_interactions_weekdays, "model_interactions_weekdays.csv", row.names = FALSE)
```

```{r}
# Extract required columns
C_data <- Personality_reward_daily_weekdays[c("C", "reward_scheme", "daily_amount")]

# View first few rows to ensure correct extraction
head(C_data)

# Check for a visual trend between N and daily_amount via scatterplot
plot(C_data$C, C_data$daily_amount, main="C Index vs Daily Amount", xlab="C Index", ylab="Daily Amount")

# Conduct linear regression analysis on N and daily_amount to check if N has a significant effect on daily_amount
model <- lm(daily_amount ~ C, data=C_data)
summary(model)

# Split the data into high N group and low N group
high_O_data <- subset(O_data, O > 3)
low_O_data <- subset(O_data, O <= 3)

# Run linear model for high N group
model_high <- lm(daily_amount ~ O, data=high_O_data)
summary(model_high)

# Run linear model for low N group
model_low <- lm(daily_amount ~ N, data=low_N_data)
summary(model_low)

```

```{r}
#Data Visualisation

# Calculate mean values
mean_values <- Personality_reward_daily %>%
  group_by(reward_condition) %>%
  summarise(mean_amount = mean(daily_amount))
mean_weekdays_values <- Personality_reward_daily_weekdays %>%
  group_by(reward_condition) %>%
  summarise(mean_amount = mean(daily_amount))
mean_weekend_values <- Personality_reward_daily_weekend %>%
  group_by(reward_condition) %>%
  summarise(mean_amount = mean(daily_amount))

# Boxplot
myColors <- c("condition1" = "#C59AE2", "condition2" = "#F08080", "condition3" = "#9AE2CC", "condition4" = "#A2E29A")

violin_plot_1 <- ggplot(Personality_reward_daily, aes(x = reward_condition, y = daily_amount, fill = reward_condition)) +
  scale_fill_manual(values = myColors) +
  geom_violin(alpha=0.8) +
  geom_boxplot(width = 0.05, fill = "white", alpha = 0.5) +
  geom_point(data = mean_values, aes(x = reward_condition, y = mean_amount), color = myColors, size = 2) +
  labs(x = "Reward Condition", y = "Daily Amount", fill = "Reward Condition") +
  theme_bw() +
  theme(legend.position = "none")
ggsave(filename = "Reward_Condition.png", plot = violin_plot_1, width = 6, height = 4, dpi = 300)


violin_plot_2 <- ggplot(Personality_reward_daily_weekdays, aes(x = reward_condition, y = daily_amount, fill = reward_condition)) +
  scale_fill_manual(values = myColors) +
  geom_violin(alpha=0.8) +
  geom_boxplot(width = 0.05, fill = "white", alpha = 0.5) +
  geom_point(data = mean_values, aes(x = reward_condition, y = mean_amount), color = myColors, size = 2) +
  labs(x = "Reward Condition", y = "Weekdays Daily Amount", fill = "Reward Condition") +
  theme_bw() +
  theme(legend.position = "none")
ggsave(filename = "Reward_Condition_weekdays.png", plot = violin_plot_2, width = 6, height = 4, dpi = 300)

violin_plot_3 <- ggplot(Personality_reward_daily_weekend, aes(x = reward_condition, y = daily_amount, fill = reward_condition)) +
  scale_fill_manual(values = myColors) +
  geom_violin(alpha=0.8) +
  geom_boxplot(width = 0.05, fill = "white", alpha = 0.5) +
  geom_point(data = mean_values, aes(x = reward_condition, y = mean_amount), color = myColors, size = 2) +
  labs(x = "Reward Condition", y = "Weekend Daily Amount", fill = "Reward Condition") +
  theme_bw() +
  theme(legend.position = "none")
ggsave(filename = "Reward_Condition_Weekend.png", plot = violin_plot_3, width = 6, height = 4, dpi = 300)

# Convert the data to long format
long_data <- Personality_reward_daily_weekdays %>%
  pivot_longer(cols = c(O, C, E, A, N), names_to = "personality_trait", values_to = "trait_value")

#Openness

Openness_plot <- ggplot() +
  geom_point(data = Personality_reward_daily[Personality_reward_daily$reward_scheme == "scheme2",], 
             aes(x = O, y = daily_amount, color = reward_scheme), alpha = 0.6) +
  geom_smooth(data = Personality_reward_daily[Personality_reward_daily$reward_scheme == "scheme2",], 
              aes(x = O, y = daily_amount, color = reward_scheme), method = "lm", se = FALSE, size = 1) +
  geom_point(data = Personality_reward_daily[Personality_reward_daily$reward_scheme != "scheme2",], 
             aes(x = O, y = daily_amount, color = reward_scheme), alpha = 0.3) +
  geom_smooth(data = Personality_reward_daily[Personality_reward_daily$reward_scheme != "scheme2",], 
              aes(x = O, y = daily_amount, color = reward_scheme), method = "lm", se = FALSE, linetype = "dashed", size = 0.5) +
  labs(x = "Openness", y = "Daily Amount") +
  theme_minimal()
print(Openness_plot)
ggsave(filename = "Openness.png", plot = Openness_plot, width = 6, height = 4, dpi = 300)

Openness_weekdays_plot <- ggplot() +
  geom_point(data = Personality_reward_daily_weekdays[Personality_reward_daily_weekdays$reward_condition == "condition2",], 
             aes(x = O, y = daily_amount, color = reward_condition), alpha = 0.6) +
  geom_smooth(data = Personality_reward_daily_weekdays[Personality_reward_daily_weekdays$reward_condition == "condition2",], 
              aes(x = O, y = daily_amount, color = reward_condition), method = "lm", se = FALSE, size = 1) +
  geom_point(data = Personality_reward_daily_weekdays[Personality_reward_daily_weekdays$reward_condition != "condition2",], 
             aes(x = O, y = daily_amount, color = reward_condition), alpha = 0.3) +
  geom_smooth(data = Personality_reward_daily_weekdays[Personality_reward_daily_weekdays$reward_condition != "condition2",], 
              aes(x = O, y = daily_amount, color = reward_condition), method = "lm", se = FALSE, linetype = "dashed", size = 0.5) +
  labs(x = "Openness", y = "Weekdays Daily Amount") +
  theme_minimal()
print(Openness_weekdays_plot)
ggsave(filename = "Openness_weekdays.png", plot = Openness_weekdays_plot, width = 6, height = 4, dpi = 300)

#Extraversion
Extraversion_weekdays_plot <- ggplot() +
  geom_point(data = Personality_reward_daily_weekdays[Personality_reward_daily_weekdays$reward_condition %in% c("condition2", "condition3", "condition1", "condition4"),], 
             aes(x = E, y = daily_amount, color = reward_condition), alpha = 0.6) +
  geom_smooth(data = Personality_reward_daily_weekdays[Personality_reward_daily_weekdays$reward_condition == "condition2",], 
              aes(x = E, y = daily_amount, color = reward_condition), method = "lm", se = FALSE, size = 1) +
  geom_smooth(data = Personality_reward_daily_weekdays[Personality_reward_daily_weekdays$reward_condition %in% c("condition3", "condition1", "condition4"),], 
              aes(x = E, y = daily_amount, color = reward_condition), method = "lm", se = FALSE, linetype = "dashed", size = 0.5) +
  labs(x = "Extraversion", y = "Weekdays Daily Amount") +
  theme_minimal()
ggsave("Extraversion_weekdays.png", width = 6, height = 4, dpi = 300)

Extraversion_weekend_plot <- ggplot() +
  geom_point(data = Personality_reward_daily_weekend[Personality_reward_daily_weekend$reward_condition %in% c("condition2"),], 
             aes(x = E, y = daily_amount, color = reward_condition), alpha = 0.6) +
  geom_smooth(data = Personality_reward_daily_weekend[Personality_reward_daily_weekend$reward_condition %in% c("condition2"),], 
              aes(x = E, y = daily_amount, color = reward_condition), method = "lm", se = FALSE, size = 1) +
  geom_point(data = Personality_reward_daily_weekend[Personality_reward_daily_weekend$reward_condition %in% c("condition1", "condition3", "condition4"),], 
             aes(x = E, y = daily_amount, color = reward_condition), alpha = 0.3) +
  geom_smooth(data = Personality_reward_daily_weekend[Personality_reward_daily_weekend$reward_condition %in% c("condition1", "condition3", "condition4"),], 
              aes(x = E, y = daily_amount, color = reward_condition), method = "lm", se = FALSE, linetype = "dashed", size = 0.5) +
  labs(x = "Extraversion", y = "Weekend Daily Amount") +
  theme_minimal()

print(Extraversion_weekend_plot)

ggsave("Extraversion_weekend.png", width = 6, height = 4, dpi = 300)

#Agreeableness
Agreeableness_plot <- ggplot(Personality_reward_daily, aes(x = A, y = daily_amount, color = reward_condition)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "Agreeableness", y = "Daily Amount") +
  theme_minimal()
ggsave("Agreeableness.png", width = 6, height = 4, dpi = 300)

Agreeableness_weekdays_plot <- ggplot(Personality_reward_daily_weekdays, aes(x = A, y = daily_amount, color = reward_condition)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "Agreeableness", y = "Weekdays Daily Amount") +
  theme_minimal()
ggsave("Agreeableness_weekdays.png", width = 6, height = 4, dpi = 300)
```
